CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "SMTPAccount" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" character varying(255) NOT NULL,
    "Password" character varying(512) NOT NULL,
    "Description" character varying(255) NOT NULL,
    CONSTRAINT "PK_SMTPAccount" PRIMARY KEY ("Id")
);

CREATE TABLE "User" (
    "Id" character varying(255) NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Email" character varying(254) NOT NULL,
    "Admin" boolean NOT NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("Id")
);

CREATE TABLE "Message" (
    "Id" character varying(255) NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "SenderName" character varying(255) NOT NULL,
    "SenderEmail" character varying(254) NOT NULL,
    "Subject" character varying(255) NOT NULL,
    "AttachmentCount" integer NOT NULL,
    "UserId" character varying(255) NOT NULL,
    CONSTRAINT "PK_Message" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Message_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Profile" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TimeZone" character varying(100) NOT NULL,
    "DateFormat" character varying(50) NOT NULL,
    "TimeFormat" character varying(50) NOT NULL,
    "UserId" character varying(255) NOT NULL,
    CONSTRAINT "PK_Profile" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Profile_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Message_UserId" ON "Message" ("UserId");

CREATE UNIQUE INDEX "IX_Profile_UserId" ON "Profile" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505195242_Initial', '10.0.7');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505205424_Init', '10.0.7');

COMMIT;

