name: Run Tests

on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: main
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10
        
      - name: Load test environment variables
        run: |
          echo "${{ secrets.TEST_ENV_VARS }}" >> $GITHUB_ENV

      - name: Allow binding to privileged ports
        run: sudo setcap 'cap_net_bind_service=+ep' $(which dotnet)

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test
        working-directory: ./Tests
